### PR TITLE
add MinGW compilation support

### PR DESCRIPTION
**Pull request by tupoy-ya**
# Changes in this PR
- Added cmake project generation
- Added MinGW compilation support
- Added compile instruction to the README.md
- Renamed a few thousand BOOL's to bool for no reason

### CODE REVIEW

**Comment by Faint0002** [comment]
Never thought of that, I appreciate this PR.  I would like you to allow compilation with VS still. Maybe setup a custom build in VS?

**Comment by tupoy-ya** [comment]
CMake will generate VS solution by default on windows.

**Comment by Faint0002** [comment]
It'll be fine, no big deal. I had it there because I had issues with it in the past.

**Comment by Faint0002** [comment]
> Sorry i removed a line about Visual C++ in the README because i though it was about having Visual C++ compiler not the redistributable.

Hey uh, your CMakeLists are messed up. Could you create a new PR fixing them?

**Comment by Faint0002** [comment]
Nvm

**Pull request merged**
